### ISSUE TITLE
Docker - Slides

### ISSUE THREAD

**Issue by RandomSort** [Praqma/reveals#10]
- [ ] Add placeholder slides showing the main storyline
- [ ] Add initial slides for actual content
- [ ] Flesh out slides
- [ ] Polish design

**Comment by sofusalbertsen** [comment]
Starting point: https://drive.google.com/drive/u/0/folders/0B5wlTv9jWGPucjU4dnQ0MDJJRjA

**Comment by sofusalbertsen** [comment]
We got .5 hours more this time than last: Is there anything else we need to include into the material?

**Comment by RandomSort** [comment]
I think it is generally better to go more indepth with the material that we
already have.

**Comment by sofusalbertsen** [comment]
Make more focus about docker network/ports: -P, -p, EXPOSE, and in docker compose
Should they actually know anything about docker compose? What does docker compose give the students in order to accomplish something on Friday.
We will not touch uppon docker swarm + compose.
So slide 72, and down is excluded from CodeAcc but still kept in order for the slides to be reusable.
ref #40

**Comment by sofusalbertsen** [comment]
Should they actually know anything about docker compose? What does docker compose give the students in order to accomplish something on Friday.

**Comment by sofusalbertsen** [comment]
We will not touch uppon docker swarm + compose.
So slide 72, and down is excluded from CodeAcc but still kept in order for the slides to be reusable.
