### ISSUE TITLE
Tests and test types - slides

### ISSUE THREAD

**Issue by RandomSort** [Praqma/reveals#8]
- [ ] Add placeholder slides showing the main storyline
- [ ] Add initial slides for actual content
- [ ] Flesh out slides
- [ ] Polish design 
- [ ] Exercises

**Comment by JKrag** [comment]
@sofusalbertsen and I discussed this today. The best idea so far is to use the go webserver combined with the roman numerals converter (or something similar). This allows for distinguishing between unit tests of the calculations and functional tests of the rest-api endpoints etc.


- Some code without tests: write the test
- some test without code: write the code (has to be very simple)
- Examples of different types of tests
- documentation of how to run the different types

**Comment by sofusalbertsen** [comment]
Message sent to Jenny and Emily

**Comment by sofusalbertsen** [comment]
jennyb [2:39 PM] 
Make sure to understand what the customer needs.  If they are prioritising time, maybe they don't need a extensively tested product, but if they are into heart surgery or self driving cars that's another story.

Test in the software development from start - testing starts already when the customer - company relationship has been established and will be present in the process throughout, otherwise it's just more or less random checking of functionality.

You can't test everything.  Code coverage is just a measurement.

The best test is whether it works in a customer environment.

Please don't make big changes.  If you make big changes it's really hard to track down where and when the product broke. Make small changes checked often instead, that way the risk for being unable to deliver to your customer gets smaller.

[2:40]  
Also testware is software too, and should adhere to the same quality standards as production code.
